apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: banking-system
data:
  # Single database URL for all services
  DB_URL: jdbc:postgresql://postgres-service:5432/bankingdb

  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "465"

  AUTH_SERVICE_URL: http://auth-service:8081
  ACCOUNT_SERVICE_URL: http://account-service:8082
  TRANSACTION_SERVICE_URL: http://transaction-service:8083
  NOTIFICATION_SERVICE_URL: http://notification-service:8084
  AUDIT_SERVICE_URL: http://audit-service:8085
  FRAUD_SERVICE_URL: http://fraud-service:8086
  APPROVAL_SERVICE_URL: http://approval-service:8087