apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking-system
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: "1234567Steven..,"
  JWT_SECRET: u8F3nD9sK2qL1vR5bX7zW6pT4mQ0yA8e
  MAIL_USERNAME: ekehsteven2@gmail.com
  MAIL_PASSWORD: "gzbs oooi akch phbv"