package com.steve.account_service.event;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TransactionEvent {
    private String transactionId;    // unique ID generated by account-service
    private String accountNumber;
    private String userEmail;
    private BigDecimal amount;       // BigDecimal not double
    private String type;             // DEPOSIT or WITHDRAWAL
    private LocalDateTime timestamp;
}